const TEXT_BLACK = '#495057';
const TEXT_GRAY = '#868E96';
const TEXT_WHITE = '#FFFFFF';
const PRIMARY_DEEP_YELLOW = '#FEE25D';
const PRIMARY_DEEP_GREEN = '#0B7545';
const PRIMARY_LIGHT_YELLOW = '#FFFCDA';
const BORDER_LIGHT_GRAY = '#EBEBEB';
const BORDER_DARK_GRAY = '#A3A3A3';
const BACKGROUND_LIGHT_GRAY = '#F7F7F7';
const BACKGROUND_LIGHT_WHITE = '#FFFFFF';
const BACKGROUND_DEEP_GRAY = '#EBEBEB';
const ITEM_COLOR = ['E21B3C', '1368CE', 'D89E00', '26890C'];

export {
  TEXT_BLACK,
  TEXT_GRAY,
  TEXT_WHITE,
  PRIMARY_DEEP_YELLOW,
  PRIMARY_DEEP_GREEN,
  PRIMARY_LIGHT_YELLOW,
  BORDER_LIGHT_GRAY,
  BORDER_DARK_GRAY,
  BACKGROUND_LIGHT_GRAY,
  BACKGROUND_LIGHT_WHITE,
  BACKGROUND_DEEP_GRAY,
  ITEM_COLOR,
};
