const BUTTON_WIDTH = '200px';
const BUTTON_HEIGHT = '50px';
const BUTTON_RADIUS = '4px';
const BUTTON_MARGIN_TOP = '15px';
const FOOTER_MARGIN_BOTTOM = '15px';

export {
  BUTTON_WIDTH,
  BUTTON_HEIGHT,
  BUTTON_RADIUS,
  BUTTON_MARGIN_TOP,
  FOOTER_MARGIN_BOTTOM,
};
